scan imporvements

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,27 +24,52 @@ jobs:
 
       - name: Lint
         run: npm run lint
+        continue-on-error: true
 
-      - name: Run tests
-        run: npm test
-
-      - name: Run Snyk to check for vulnerabilities
+      - name: Run Snyk check for vulnerabilities
         uses: snyk/actions/node@master
+        continue-on-error: true
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           command: monitor
 
-      - name: TruffleHog Scan
+      - name: Run TruffleHog scan for secrets
         id: trufflehog
         uses: trufflesecurity/trufflehog@main
-        #continue-on-error: true
+        continue-on-error: true
         with:
           path: ./
           base: ""
           head: HEAD
           extra_args: --debug
 
-      #- name: Scan Results Status
-      #  if: steps.trufflehog.outcome == 'failure'
-      #  run: exit 1
+      #- name: SonarQube Scan
+      #  continue-on-error: true
+      #  uses: SonarSource/sonarqube-scan-action@v7.0.0
+      #  with:
+      #    projectBaseDir: app/src
+      #    args: >
+      #      -Dsonar.organization=my-organization
+      #      "-Dsonar.projectName=My Project"
+      #      -Dsonar.projectKey=my-projectkey
+      #      -Dsonar.sources=src/
+      #      -Dsonar.tests=tests/
+      #      -Dsonar.verbose=true
+
+      - name: Trivy Scan
+        id: trivy
+        uses: ./.github/workflows/trivy-scan.yml
+        continue-on-error: true
+        with:
+          image: devops-app:${{ github.sha }}
+
+      - name: Run tests
+        continue-on-error: true
+        run: npm test
+
+      - name: Fail if any step failed
+        if: ${{ steps.lint.outcome == 'failure' || steps.snyk.outcome == 'failure' || steps.trufflehog.outcome == 'failure' || steps.test.outcome == 'failure' || steps.trivy.outcome == 'failure' }}
+        run: |
+          echo "One or more checks failed. Failing the workflow."
+          exit 1
